baseURL = 'https://tvvcc.org/'
languageCode = 'en-us'
title = 'Treasure Valley Vintage Computer Club'
theme = '1995'
disableHugoGeneratorInject = true

[params]
  subtitle = "An open club for vintage computing enthusiasts in Boise, Idaho"
  keywords = "Boise, retro, vintage, computer, computing, gaming, electronics"
  discordURL = "https://discord.gg/QHU4cwrSTt"
  welcomeText = "Welcome to the home of the Treasure Valley Vintage Computer Club! We are a Boise, ID based collective of vintage computing enthusiasts. Join us to share projects, get help with your vintage treasures, and connect with fellow retro computing fans."

[pagination]
  pagerSize = 10
